CREATE TABLE PET
(P_NUM VARCHAR2(10) PRIMARY KEY, P_KIND VARCHAR2(20) );

CREATE TABLE CLIENTS 
(P_NUM VARCHAR2(10) PRIMARY KEY REFERENCES PET(P_NUM) , C_NAME VARCHAR2(30), C_PHONE VARCHAR2(20) UNIQUE,
 C_ADDR VARCHAR2(70) );
 
CREATE TABLE BUSINESS
(B_NUM VARCHAR2(10) PRIMARY KEY, B_NAME VARCHAR2(20) );

CREATE TABLE EMPLOYEES
(E_NUM  VARCHAR2(10) PRIMARY KEY, B_NUM VARCHAR2(10) REFERENCES BUSINESS(B_NUM), E_ID VARCHAR2(20), E_PW VARCHAR2(20),
 E_NAME VARCHAR2(20), E_PHONE VARCHAR2(30), E_HIRE DATE DEFAULT SYSDATE );
 
 CREATE TABLE RESERVATE
(R_NUM INTEGER PRIMARY KEY, E_NUM VARCHAR2(10) REFERENCES EMPLOYEES(E_NUM),
 P_NUM VARCHAR2(10) REFERENCES PET(P_NUM),C_PHONE REFERENCES CLIENTS(C_PHONE),
 R_DATE DATE ,R_TIME TIMESTAMP, R_ETC VARCHAR2(50),PICKUP VARCHAR2(2) );
 
  CREATE TABLE FAQ
(FAQ_NUM INTEGER PRIMARY KEY, FAQ_HEAD VARCHAR2(20), FAQ_BODY VARCHAR2(50));

CREATE TABLE OFFCOL
(O_NUM INTEGER PRIMARY KEY, O_NAME VARCHAR2(10));

 CREATE TABLE EOFF
 (O_NUM INTEGER PRIMARY KEY REFERENCES OFFCOL(O_NUM), E_NUM VARCHAR2(10) REFERENCES EMPLOYEES(E_NUM),
  O_DATE DATE , O_TIME TIMESTAMP);
  
  //PROJECT01 테이블 생성코드