--회원
CREATE TABLE USERLIST
(
U_ID        VARCHAR2(30) PRIMARY KEY ,
USERPW      VARCHAR2(30),
USERNAME    VARCHAR2(20),
EMAIL       VARCHAR2(60),
GENDER      VARCHAR2(10),
PHONE       VARCHAR2(20),
U_SIDO      VARCHAR2(10),
U_GUGUN     VARCHAR2(10)
);


--고수
CREATE TABLE GOSU
(G_NUM VARCHAR2(10) PRIMARY KEY, U_ID VARCHAR2(30) REFERENCES USERLIST(U_ID));

--대분류
CREATE TABLE BIGLIST
(
BI_NUM      VARCHAR2(10) PRIMARY KEY ,
BI_NAME     VARCHAR2(20)
);

--중분류
CREATE TABLE MIDLIST
(
MID_NUM      VARCHAR2(10) PRIMARY KEY ,
BI_NUM       VARCHAR2(10) REFERENCES BIGLIST(BI_NUM),
MID_NAME     VARCHAR2(30)
);

--고수업무리스트
CREATE TABLE GWORK
(W_NUM VARCHAR2(20) PRIMARY KEY, G_NUM VARCHAR2(30) REFERENCES GOSU(G_NUM),
 MID_NUM VARCHAR2(10) REFERENCES MIDLIST(MID_NUM),
 SDATE DATE , EDATE DATE, PRICE VARCHAR2(20), WSIDO VARCHAR2(20),
PRMESSAGE VARCHAR2(60)   
);

--거래리스트
CREATE TABLE GEORAE
(
GEORAE_CODE VARCHAR2(20) PRIMARY KEY ,
W_NUM       VARCHAR2(20) REFERENCES GWORK(W_NUM),
M_MESSAGE   VARCHAR2(10) ,
G_MESSAGE   VARCHAR2(10) ,
G_CHECK     VARCHAR2(10) ,
G_DATE      DATE DEFAULT SYSDATE
);


--메시지리스트
CREATE TABLE MESSAGE 
(MESSNUM VARCHAR2(20) PRIMARY KEY,
GEORAE_CODE VARCHAR2(20) REFERENCES GEORAE(GEORAE_CODE),
U_ID VARCHAR2(30) REFERENCES USERLIST(U_ID),
G_NUM VARCHAR2(20) REFERENCES GOSU(G_NUM),
MREAD VARCHAR2(10)
);

--FAQ리스트
CREATE TABLE FAQ
(
FAQ_CODE    VARCHAR2(10) PRIMARY KEY ,
U_ID        VARCHAR2(30) REFERENCES USERLIST(U_ID),
F_DATE      DATE DEFAULT SYSDATE,
F_HEAD      VARCHAR2(20),
F_BODY      VARCHAR2(150),
REPLY       VARCHAR2(150),
F_CHECK     VARCHAR2(10)
);








-----------------------------------------------------------------------------

-- 데이터
-- 회원 추가
INSERT INTO USERLIST VALUES ( 'HONG', 'H1234', '홍길동',
'hong01@naver.com', '남', '010-1234-5678', '부산시', '중구' );

-- 대분류 추가
INSERT INTO BIGLIST VALUES ( 'B01', '자동차' );
INSERT INTO BIGLIST VALUES ( 'B02', '집수리 및 설치' );
INSERT INTO BIGLIST VALUES ( 'B03', '집청소' );
INSERT INTO BIGLIST VALUES ( 'B04', '기타' );

-- 중분류 추가
INSERT INTO MIDLIST VALUES ( 'M01', 'B01', '블랙박스 설치' );
INSERT INTO MIDLIST VALUES ( 'M02', 'B01', '네이게이션 설치' );
INSERT INTO MIDLIST VALUES ( 'M03', 'B01', '차 선팅' );
INSERT INTO MIDLIST VALUES ( 'M04', 'B01', '출장 세차' );
INSERT INTO MIDLIST VALUES ( 'M05', 'B01', '내부 시트 부착' );
INSERT INTO MIDLIST VALUES ( 'M06', 'B01', '자동차 구매 동행' );

INSERT INTO MIDLIST VALUES ( 'M07', 'B02', '블라인드/커튼 설치' );
INSERT INTO MIDLIST VALUES ( 'M08', 'B02', '조명 설치/교체' );
INSERT INTO MIDLIST VALUES ( 'M09', 'B02', '시트지 붙이기/도배' );
INSERT INTO MIDLIST VALUES ( 'M10', 'B02', '전자제품 설치' );
INSERT INTO MIDLIST VALUES ( 'M11', 'B02', '방범창 설치' );

INSERT INTO MIDLIST VALUES ( 'M12', 'B03', '에어컨 청소' );
INSERT INTO MIDLIST VALUES ( 'M13', 'B03', '세탁기 청소' );
INSERT INTO MIDLIST VALUES ( 'M14', 'B03', '화장실 청소' );
INSERT INTO MIDLIST VALUES ( 'M15', 'B03', '창틀 청소' );
INSERT INTO MIDLIST VALUES ( 'M16', 'B03', '부엌 선반 정리' );
INSERT INTO MIDLIST VALUES ( 'M17', 'B03', '가구 배치/철거' );

INSERT INTO MIDLIST VALUES ( 'M18', 'B01', '기타' );
INSERT INTO MIDLIST VALUES ( 'M19', 'B02', '기타' );
INSERT INTO MIDLIST VALUES ( 'M20', 'B03', '기타' );

ALTER TABLE GWORK ADD WGUGUN VARCHAR2(20);

-----------------------------------------------------------------
INSERT INTO GOSU VALUES ( 'G01', 'HONG');

commit;

create sequence gwork_Num
                increment by 1
                start with 1
                minvalue 1
                maxvalue 9999
                nocycle
                nocache
                noorder;